logstash-indexer-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
logstash-indexer:
  restart: always
  tty: true
  volumes_from:
  - logstash-indexer-config
  mem_reservation: 5369757696 
  command:
  - logstash
  - -f
  - /etc/logstash
  image: zenprocess/logstash:5
  environment:
    JAVA_OPTS: -Xmx5g -Xms1g
  external_links:
  - ${elasticsearch_link}:elasticsearch
  stdin_open: true
  volumes:
  - /home/XML:/home/XML
  labels:
    io.rancher.sidekicks: logstash-indexer-config
    io.rancher.container.hostname_override: container_name
