.catalog:
  name: "Logstash"
  version: "5.1.2 Sili Version 2 EmptyConfig"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "indexer_inputs"
      description: |
        Logstash collection tier inputs. These will be added
        directly to input { } section of logstash.conf
      label: "Logstash inputs"
      type: "multiline"
      required: true
      default: ""
    - variable: "indexer_filters"
      description: |
        Logstash indexing tier filters. These will be added
        directly to filter { } section of logstash.conf
      label: "Logstash filters"
      type: "multiline"
      required: false
      default: ""
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: ""
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch
        cluster.
      label: "Elasticsearch stack/service"
      default: "es/elasticsearch-clients"
      required: true
      type: "service"
logstash-indexer:
  metadata:
    logstash:
      inputs: |
        ${indexer_inputs}
      filters: |
        ${indexer_filters}
      outputs: |
        ${indexer_outputs}
