.catalog:
  name: "Logstash"
  version: "5.2 Sili Version"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "indexer_inputs"
      description: |
        Logstash collection tier inputs. These will be added
        directly to input { } section of logstash.conf
      label: "Logstash inputs"
      type: "multiline"
      required: true
      default: |
        file {
          path => "/home/XML/*.json"
          start_position => "beginning"
          sincedb_path => "/dev/null"
          type => "json"
          codec => "json"
        }
    - variable: "indexer_filters"
      description: |
        Logstash indexing tier filters. These will be added
        directly to filter { } section of logstash.conf
      label: "Logstash filters"
      type: "multiline"
      required: false
      default: |
        if ( [channel][job] ) {
          split {
              field => "channel[job]"
          }
        ruby {
            code => "require 'digest/md5'; 
            hasher=String.new
            hasher << (event['channel']['job']['job_title']['$'] or '')
            hasher << (event['channel']['job']['link']['$'] or '')
            event['hash'] = Digest::MD5.hexdigest(hasher)
            print (Digest::MD5.hexdigest(hasher)) "

            }
        }
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
        elasticsearch {
          hosts => ["elasticsearch.rancher.internal:9200"]
          index => "jobs"
          action => "update"
          doc_as_upsert => true
          document_id => "%{[hash]}
        }
        stdout {
          codec => rubydebug
        }
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch
        cluster.
      label: "Elasticsearch stack/service"
      default: "es/elasticsearch-clients"
      required: true
      type: "service"
logstash-indexer:
  metadata:
    logstash:
      inputs: |
        ${indexer_inputs}
      filters: |
        ${indexer_filters}
      outputs: |
        ${indexer_outputs}
